config/routes.rb
Rails.application.routes.draw do

  resources :products do
    get "delete"
  end

  get 'contacts/index'

  get 'features/button'
  get 'features/tab'
  get 'features/testmonial'
  get 'features/typography'
  get 'features/icon'

  get 'blogs/blog'
  get 'blogs/blog2'
  get 'blogs/post'
  get 'blogs/post2'

  get 'portfolios/index'
  get 'portfolios/portfolio2'
  get 'portfolios/portfolio3'
  get 'portfolios/portfolio4'
  get 'portfolios/post'

  
  get 'homes/index'
  get 'homes/index2'
  get 'homes/index3'
  

  root  'homes#index'

end

app/models/product.rb
class Product < ActiveRecord::Base
  validates :name, presence: true
  validates :price, presence: true,
            numericality: true,
            format: { :with => /\A\d{1,4}(\.\d{0,2})?\z/ }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  def blog
  end

  def blog2
  end

  def post
  end

  def post2
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
  end
end

app/controllers/features_controller.rb
class FeaturesController < ApplicationController
  def button
  end

  def tab
  end

  def testmonial
  end

  def typography
  end

  def icon
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
  
  def index2
  end
  def index3
  end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  def index
  end

  def portfolio2
  end

  def portfolio3
  end

  def portfolio4
  end

  def post
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  respond_to :html, :js
  
  def index
    @products = Product.all
  end
 
  def show
    @product = Product.find(params[:id])
  end
 
  def new
    @product = Product.new
  end
 
  def create
    @products = Product.all
    @product = Product.create(product_params)
  end
 
  def edit
    @product = Product.find(params[:id])
  end
 
  def update
    @products = Product.all
    @product = Product.find(params[:id])
    
    @product.update_attributes(product_params)
  end
 
  def delete
    @product = Product.find(params[:product_id])
  end
 
  def destroy
    @products = Product.all
    @product = Product.find(params[:id])
    @product.destroy
  end
 
private
  def product_params
    params.require(:product).permit(:name, :price)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/features_helper.rb
module FeaturesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/blogs/_blog.html.haml
= render 'head'
/ Begin Post
.post
  %a{:href => "post.html"}
    %img{:alt => "", :src => "/style/images/art/slide1.jpg"}/
  / Begin Info
  .info
    / Begin Date
    .date
      .day 24
      .month Sep
    / End Date
    / Begin Meta
    .meta
      %h3.title
        %a{:href => "post.html"} Malesuada Condimentum Inceptos Vehicula
      .comments
        %a{:href => "#"} 11 Comments
      .tags
        %a{:href => "#"} photography,
        %a{:href => "#"} manipulation,
        %a{:href => "#"} journal
    / End Meta
  .clear
  / End Info
  %p
    Curabitur blandit tempus porttitor. Donec ullamcorper nulla non metus auctor fringilla. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod. Praesent commodo cursus magna, vel scelerisque nisl consectetur et.
    %a.more{:href => "post.html"} Continue reading...
/ End Post
/ Begin Post
.post
  / Begin Slider
  .slider
    %div
      %img{:alt => "", :src => "/style/images/art/slide2.jpg"}/
    %div
      %img{:alt => "", :src => "/style/images/art/slide4.jpg"}/
  / End Slider
  / Begin Info
  .info
    / Begin Date
    .date
      .day 24
      .month Sep
    / End Date
    / Begin Meta
    .meta
      %h3.title
        %a{:href => "post.html"} Malesuada Condimentum Inceptos Vehicula
      .comments
        %a{:href => "#"} 13 Comments
      .tags
        %a{:href => "#"} photography,
        %a{:href => "#"} manipulation,
        %a{:href => "#"} journal
    / End Meta
  .clear
  / End Info
  %p
    Curabitur blandit tempus porttitor. Donec ullamcorper nulla non metus auctor fringilla. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod. Praesent commodo cursus magna, vel scelerisque nisl consectetur et.
    %a.more{:href => "post.html"} Continue reading...
/ End Post
/ Begin Post
.post
  %a{:href => "post.html"}
    %img{:alt => "", :src => "/style/images/art/slide3.jpg"}/
  / Begin Info
  .info
    / Begin Date
    .date
      .day 24
      .month Sep
    / End Date
    / Begin Meta
    .meta
      %h3.title
        %a{:href => "post.html"} Malesuada Condimentum Inceptos Vehicula
      .comments
        %a{:href => "#"} 13 Comments
      .tags
        %a{:href => "#"} photography,
        %a{:href => "#"} manipulation,
        %a{:href => "#"} journal
    / End Meta
  .clear
  / End Info
  %p Curabitur blandit tempus porttitor. Donec ullamcorper nulla non metus auctor fringilla. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod. Praesent commodo cursus magna, vel scelerisque nisl consectetur et.
/ End Post
/ Begin Post
.post
  %a{:href => "post.html"}
    %img{:alt => "", :src => "/style/images/art/slide4.jpg"}/
  / Begin Info
  .info
    / Begin Date
    .date
      .day 24
      .month Sep
    / End Date
    / Begin Meta
    .meta
      %h3.title
        %a{:href => "post.html"} Malesuada Condimentum Inceptos Vehicula
      .comments
        %a{:href => "#"} 13 Comments
      .tags
        %a{:href => "#"} photography,
        %a{:href => "#"} manipulation,
        %a{:href => "#"} journal
    / End Meta
  .clear
  / End Info
  %p Curabitur blandit tempus porttitor. Donec ullamcorper nulla non metus auctor fringilla. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod. Praesent commodo cursus magna, vel scelerisque nisl consectetur et.
/ End Post
/ Begin Page Navi
= render 'pagenavi'

app/views/blogs/_blog2.html.haml
= render 'head'
.primary
  / Begin Post
  .post
    %a{:href => "post2.html"}
      %img{:alt => "", :src => "/style/images/art/blog2-1.jpg"}/
    / Begin Info
    .info
      / Begin Date
      .date
        .day 24
        .month Sep
      / End Date
      / Begin Meta
      .meta
        %h3.title
          %a{:href => "post2.html"} Malesuada Condimentum Inceptos Vehicula
        .comments
          %a{:href => "#"} 11 Comments
        .tags
          %a{:href => "#"} photography,
          %a{:href => "#"} manipulation,
          %a{:href => "#"} journal
      / End Meta
    .clear
    / End Info
    %p
      Curabitur blandit tempus porttitor. Donec ullamcorper nulla non metus auctor fringilla. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod. Praesent commodo cursus magna, vel scelerisque nisl consectetur et.
      %a.more{:href => "post2.html"} Continue reading...
  / End Post
  / Begin Post
  .post
    / Begin Slider
    .slider
      %div
        %img{:alt => "", :src => "/style/images/art/blog2-2.jpg"}/
      %div
        %img{:alt => "", :src => "/style/images/art/blog2-4.jpg"}/
    / End Slider
    / Begin Info
    .info
      / Begin Date
      .date
        .day 24
        .month Sep
      / End Date
      / Begin Meta
      .meta
        %h3.title
          %a{:href => "post2.html"} Malesuada Condimentum Inceptos Vehicula
        .comments
          %a{:href => "#"} 13 Comments
        .tags
          %a{:href => "#"} photography,
          %a{:href => "#"} manipulation,
          %a{:href => "#"} journal
      / End Meta
    .clear
    / End Info
    %p
      Curabitur blandit tempus porttitor. Donec ullamcorper nulla non metus auctor fringilla. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod. Praesent commodo cursus magna, vel scelerisque nisl consectetur et.
      %a.more{:href => "post2.html"} Continue reading...
  / End Post
  / Begin Post
  .post
    %a{:href => "post2.html"}
      %img{:alt => "", :src => "/style/images/art/blog2-3.jpg"}/
    / Begin Info
    .info
      / Begin Date
      .date
        .day 24
        .month Sep
      / End Date
      / Begin Meta
      .meta
        %h3.title
          %a{:href => "post2.html"} Malesuada Condimentum Inceptos Vehicula
        .comments
          %a{:href => "#"} 13 Comments
        .tags
          %a{:href => "#"} photography,
          %a{:href => "#"} manipulation,
          %a{:href => "#"} journal
      / End Meta
    .clear
    / End Info
    %p
      Curabitur blandit tempus porttitor. Donec ullamcorper nulla non metus auctor fringilla. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod. Praesent commodo cursus magna, vel scelerisque nisl consectetur et.
      %a.more{:href => "post2.html"} Continue reading...
  / End Post
  / Begin Post
  .post
    %a{:href => "post2.html"}
      %img{:alt => "", :src => "/style/images/art/blog2-4.jpg"}/
    / Begin Info
    .info
      / Begin Date
      .date
        .day 24
        .month Sep
      / End Date
      / Begin Meta
      .meta
        %h3.title
          %a{:href => "post2.html"} Malesuada Condimentum Inceptos Vehicula
        .comments
          %a{:href => "#"} 13 Comments
        .tags
          %a{:href => "#"} photography,
          %a{:href => "#"} manipulation,
          %a{:href => "#"} journal
      / End Meta
    .clear
    / End Info
    %p Curabitur blandit tempus porttitor. Donec ullamcorper nulla non metus auctor fringilla. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod. Praesent commodo cursus magna, vel scelerisque nisl consectetur et.
  / End Post
  / Begin Page Navi
  .page-navi
    %ul
      %li
        %a.current{:href => "#"} 1
      %li
        %a{:href => "#"} 2
      %li
        %a{:href => "#"} 3
      %li
        %a{:href => "#"} ›
      %li
        %a{:href => "#"} »
  / End Page Navi
/ End Primary
/ Begin Secondary
.secondary
  .sidebox
    %h3 Categories
    %ul.sidelist
      %li
        %a{:href => "#"} Web Design (12)
      %li
        %a{:href => "#"} Photography (10)
      %li
        %a{:href => "#"} Manipulation (18)
      %li
        %a{:href => "#"} Motion Graphic (13)
      %li
        %a{:href => "#"} Graphic Design (10)
  .sidebox
    %h3 Popular Posts
    %ul.popular-posts
      %li
        %a{:href => "#"}
          %img{:alt => "", :src => "/style/images/art/s1.jpg"}/
        %h5
          %a{:href => "#"} Dolor Commodo Consectetur
        %span
          26.08.11 |
          %a{:href => "#"} 21 Comments
      %li
        %a{:href => "#"}
          %img{:alt => "", :src => "/style/images/art/s2.jpg"}/
        %h5
          %a{:href => "#"} Dolor Commodo Consectetur
        %span
          26.08.11 |
          %a{:href => "#"} 21 Comments
      %li
        %a{:href => "#"}
          %img{:alt => "", :src => "/style/images/art/s3.jpg"}/
        %h5
          %a{:href => "#"} Dolor Commodo Consectetur
        %span
          26.08.11 |
          %a{:href => "#"} 21 Comments
  .sidebox
    %h3 Custom Text
    %p Curabitur blandit tempus porttitor. Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor.
    %p Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor.
  .sidebox
    %h3 Archives
    %ul.sidelist
      %li
        %a{:href => "#"} January 2011 (12)
      %li
        %a{:href => "#"} February 2011 (10)
      %li
        %a{:href => "#"} March 2011 (18)
      %li
        %a{:href => "#"} April 2011 (13)
      %li
        %a{:href => "#"} May 2011 (10)
      %li
        %a{:href => "#"} June 2011 (18)
  .sidebox
    %h3 Tags
    %ul.sidelist
      %li
        %a{:href => "#"} Web Design (12)
      %li
        %a{:href => "#"} Photography (10)
      %li
        %a{:href => "#"} Manipulation (18)
      %li
        %a{:href => "#"} Motion Graphic (13)
      %li
        %a{:href => "#"} Graphic Design (10)
/ End Secondary
.clear

app/views/blogs/_head.html.haml
- content_for :searchbox do
  = render 'searchbox'
%h1.title Blog
.line
.intro Nullam id dolor id nibh ultricies vehicula ut id elit. Etiam porta sem malesuada magna mollis euismod. Integer posuere erat a ante venenatis dapibus posuere velit aliquet.

.sidebar-for-blog

app/views/blogs/_pagenavi.html.haml
.page-navi
  %ul
    %li
      %a.current{:href => "#"} 1
    %li
      %a{:href => "#"} 2
    %li
      %a{:href => "#"} 3
    %li
      %a{:href => "#"} ›
    %li
      %a{:href => "#"} »
/ End Page Navi

app/views/blogs/_post.html.haml
= render 'head'
/ Begin Post
.post
  %img{:alt => "", :src => "/style/images/art/slide1.jpg"}/
  / Begin Info
  .info
    / Begin Date
    .date
      .day 24
      .month Sep
    / End Date
    / Begin Meta
    .meta
      %h3.title Malesuada Condimentum Inceptos Vehicula
      .comments
        %a{:href => "#"} 11 Comments
      .tags
        %a{:href => "#"} photography,
        %a{:href => "#"} manipulation,
        %a{:href => "#"} journal
    / End Meta
  .clear
  / End Info
  %p Curabitur blandit tempus porttitor. Donec ullamcorper nulla non metus auctor fringilla. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod. Praesent commodo cursus magna, vel scelerisque nisl consectetur et.
/ End Post
/ Begin Facebook Comments
#fb-root
:javascript
  (function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) {return;}
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));
.fb-comments{"data-href" => "http://themes.iki-bir.com/caprice/post.html", "data-num-posts" => "10", "data-width" => "700"}
/ Enter your page URL here
/ End Facebook Comments

app/views/blogs/_post2.html.haml
= render 'head'
.primary
  / Begin Post
  .post
    %img{:alt => "", :src => "/style/images/art/blog2-1.jpg"}/
    / Begin Info
    .info
      / Begin Date
      .date
        .day 24
        .month Sep
      / End Date
      / Begin Meta
      .meta
        %h3.title Malesuada Condimentum Inceptos Vehicula
        .comments
          %a{:href => "#"} 11 Comments
        .tags
          %a{:href => "#"} photography,
          %a{:href => "#"} manipulation,
          %a{:href => "#"} journal
      / End Meta
    .clear
    / End Info
    %p Curabitur blandit tempus porttitor. Donec ullamcorper nulla non metus auctor fringilla. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod. Praesent commodo cursus magna, vel scelerisque nisl consectetur et.
    %p Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Curabitur blandit tempus porttitor. Etiam porta sem malesuada magna mollis euismod. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Aenean lacinia bibendum nulla sed consectetur. Donec ullamcorper nulla non metus auctor fringilla.
    %p Nulla vitae elit libero, a pharetra augue. Maecenas faucibus mollis interdum. Curabitur blandit tempus porttitor. Nullam quis risus eget urna mollis ornare vel eu leo. Cras mattis consectetur purus sit amet fermentum.
    %p Praesent commodo cursus magna, vel scelerisque nisl consectetur et. Curabitur blandit tempus porttitor. Nullam id dolor id nibh ultricies vehicula ut id elit. Maecenas faucibus mollis interdum. Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor.
    %p Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Nulla vitae elit libero, a pharetra augue. Donec id elit non mi porta gravida at eget metus. Aenean lacinia bibendum nulla sed consectetur. Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.
  / End Post
  / Begin Facebook Comments
  #fb-root
  .fb-comments{"data-href" => "http://themes.iki-bir.com/caprice/post2.html", "data-num-posts" => "10", "data-width" => "470"}
  / Enter your page URL here
  / End Facebook Comments
/ End Primary
/ Begin Secondary
.secondary
  .sidebox
    %h3 Categories
    %ul.sidelist
      %li
        %a{:href => "#"} Web Design (12)
      %li
        %a{:href => "#"} Photography (10)
      %li
        %a{:href => "#"} Manipulation (18)
      %li
        %a{:href => "#"} Motion Graphic (13)
      %li
        %a{:href => "#"} Graphic Design (10)
  .sidebox
    %h3 Popular Posts
    %ul.popular-posts
      %li
        %a{:href => "#"}
          %img{:alt => "", :src => "/style/images/art/s1.jpg"}/
        %h5
          %a{:href => "#"} Dolor Commodo Consectetur
        %span
          26.08.11 |
          %a{:href => "#"} 21 Comments
      %li
        %a{:href => "#"}
          %img{:alt => "", :src => "/style/images/art/s2.jpg"}/
        %h5
          %a{:href => "#"} Dolor Commodo Consectetur
        %span
          26.08.11 |
          %a{:href => "#"} 21 Comments
      %li
        %a{:href => "#"}
          %img{:alt => "", :src => "/style/images/art/s3.jpg"}/
        %h5
          %a{:href => "#"} Dolor Commodo Consectetur
        %span
          26.08.11 |
          %a{:href => "#"} 21 Comments
  .sidebox
    %h3 Custom Text
    %p Curabitur blandit tempus porttitor. Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor.
    %p Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor.
  .sidebox
    %h3 Archives
    %ul.sidelist
      %li
        %a{:href => "#"} January 2011 (12)
      %li
        %a{:href => "#"} February 2011 (10)
      %li
        %a{:href => "#"} March 2011 (18)
      %li
        %a{:href => "#"} April 2011 (13)
      %li
        %a{:href => "#"} May 2011 (10)
      %li
        %a{:href => "#"} June 2011 (18)
  .sidebox
    %h3 Tags
    %ul.sidelist
      %li
        %a{:href => "#"} Web Design (12)
      %li
        %a{:href => "#"} Photography (10)
      %li
        %a{:href => "#"} Manipulation (18)
      %li
        %a{:href => "#"} Motion Graphic (13)
      %li
        %a{:href => "#"} Graphic Design (10)
/ End Secondary
.clear

app/views/blogs/_searchbox.html.haml
.sidebox
  .search
    %h3 Search
    %form.searchform{:method => "get"}
      %input#s{:name => "s", :onblur => "this.value='type and hit enter'", :onfocus => "this.value=''", :type => "text", :value => "type and hit enter"}/
    .clear

app/views/blogs/blog.html.haml
= render 'blog'

app/views/blogs/blog2.html.haml
= render 'blog2'

app/views/blogs/post.html.haml
= render 'post'

app/views/blogs/post2.html.haml
= render 'post2'

app/views/contacts/index.html.haml
= render 'index'

app/views/features/button.html.haml
= render 'button'

app/views/features/icon.html.haml
= render 'icon'

app/views/features/tab.html.haml
= render 'tab'

app/views/features/testmonial.html.haml
= render 'testmonial'

app/views/features/typography.html.haml
= render 'typography'

app/views/homes/index.html.haml
= render 'index'

app/views/homes/index2.html.haml
= render 'index2'

app/views/homes/index3.html.haml
= render 'index3'

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    = content_tag :div, msg, :class => "flash_#{name}"

app/views/layouts/_navigation.html.haml
%ul.nav
  %li= link_to 'Home', root_path
  = render 'layouts/navigation_links'

app/views/layouts/_sidebar.html.haml
/ Begin Sidebar
#sidebar
	#logo
		= link_to root_path, remote: true do
			%img{alt: "Caprice", src: "/style/images/logo.png"}/
	/ Begin Menu
	#menu.menu-v
		%ul
			%li
				= link_to 'Home', homes_index_path, class:'active', remote: true
				%ul
					%li
						= link_to 'Home w/ Carousel', homes_index_path, remote: true
					%li
						= link_to 'Home w/ Portfolio', homes_index2_path, remote: true
					%li
						= link_to 'Home w/ Testimonials', homes_index3_path, remote: true
			%li
				= link_to 'Portfolio', portfolios_index_path, remote: true
				%ul
					%li
						= link_to 'Portfolio 4 Columns', portfolios_index_path, remote: true
					%li
						= link_to 'Portfolio 3 Columns', portfolios_portfolio2_path, remote: true
					%li
						= link_to 'Portfolio 2 Columns', portfolios_portfolio3_path, remote: true
					%li
						= link_to 'Portfolio 1 Columns', portfolios_portfolio4_path, remote: true
					%li
						= link_to 'Portfolio Post', portfolios_post_path, remote: true
			%li
				= link_to 'Blog', blogs_blog_path, remote: true
				%ul
					%li
						= link_to 'Blog', blogs_blog_path, remote: true
					%li
						= link_to 'Blog w/ Sidebar', blogs_blog2_path, remote: true
					%li
						= link_to 'Post', blogs_post_path
					%li
						= link_to 'Post w/ Sidebar', blogs_post2_path
			%li
				= link_to 'Features', features_button_path, remote: true
				%ul
					%li
						= link_to 'Buttons Boxes Images', features_button_path, remote: true
					%li
						= link_to 'Tabs Toggle Tables', features_tab_path, remote: true
					%li
						= link_to 'Testimonials', features_testmonial_path , remote: true
					%li
						= link_to 'Typography', features_typography_path, remote: true
					%li
						= link_to 'Service icons', features_icon_path, remote: true
			%li
				=link_to 'Contact Us', contacts_index_path, remote: true
	/ End Menu
	.sidebox
		%ul.share
			%li
				%a{href: "javascript:;"}
					%img{alt: "RSS", src: "/style/images/icon-rss.png"}/
			%li
				%a{href: "javascript:;"}
					%img{alt: "Facebook", src: "/style/images/icon-facebook.png"}/
			%li
				%a{href: "javascript:;"}
					%img{alt: "Twitter", src: "/style/images/icon-twitter.png"}/
			%li
				%a{href: "javascript:;"}
					%img{alt: "Dribbble", src: "/style/images/icon-dribbble.png"}/
			%li
				%a{href: "javascript:;"}
					%img{alt: "LinkedIn", src: "/style/images/icon-linkedin.png"}/
	#searchbox-wrapper-for-blog
		= yield :searchbox
/ End Sidebar

app/views/portfolios/index.html.haml
= render 'index'

app/views/products/_delete.html.haml
.modal-header
  %h3 Delete Product
.modal-body
  %ul.errors
  Are you sure you wish to delete
  = succeed "?" do
    %b= @product.name
.modal-footer
  = link_to "Yes, Delete This Product", product_path(@product), method: :delete, remote: true, class: "btn btn-danger"
  = link_to "No, Please Don't", "#", class: "btn", data: { dismiss: "modal" }

app/views/products/_index.html.haml
- @products.each do |product|
  %tr
    %td= product.name
    %td= number_to_currency product.price
    %td= link_to "Edit", edit_product_path(product), remote: true, class: "btn"
    %td= link_to "Delete", product_delete_path(product), remote: true, class: "btn btn-danger"

app/views/products/index.html.haml
.container
  .well
    = link_to "New Product", new_product_path, remote: true, class: "btn btn-primary"
  .new-product
  %table.table.table-bordered.table-striped
    %thead
      %tr
        %th Name
        %th Price
        %td &nbsp;
        %td &nbsp;
    %tbody.product-index
      = render "index"
#product-modal.modal.hide.fade